# Generated by Django 5.0.4 on 2024-08-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('fmri_photo', models.ImageField(upload_to='fmri_photos/')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseApp.login')),
            ],
        ),
    ]
